### ISSUE TITLE
Demo用的是UE4的什么版本？

### ISSUE THREAD

**Issue by marshal-it** [kbengine/kbengine_ue4_demo#1]

**Comment by kbengine** [comment]
4.13.2

**Comment by marshal-it** [comment]
好的。不过目前我验证的，只能到创建账户，登陆，选择角色对吧。
![image](https://cloud.githubusercontent.com/assets/3109971/20879369/723065fa-bb0e-11e6-86f0-cf571c86f3cb.png)

**Comment by marshal-it** [comment]
很强了！感谢！good!  good!

**Comment by kbengine** [comment]
还没弄完

**Comment by kbengine** [comment]
可以进游戏了

**Comment by marshal-it** [comment]
对应的服务器版本是0.9.6的demos_assets需要更新么？这边貌似在编辑器还是进不去

**Comment by marshal-it** [comment]
服务器版本是0.9.0 ？

**Comment by marshal-it** [comment]
服务器版本是0.9.0 ？

**Comment by kbengine** [comment]
都下最新开发版

**Comment by kbengine** [comment]
https://github.com/kbengine/kbengine_ue4_demo
可测试了，目前没有发布版本，服务端和客户端都使用git clone得到开发版本测试
