### ISSUE TITLE
创建一个KBE的蓝图结点，UE会崩掉，试了各种方法都无法避免崩溃

### ISSUE THREAD

**Issue by bowdar** [kbengine/kbengine_ue4_demo#4]
![default](https://cloud.githubusercontent.com/assets/3293745/25060302/4dd66cac-21cc-11e7-87d0-4338e1382eda.png)

**Comment by kbengine** [comment]
引擎什么版本？

**Comment by kbengine** [comment]
直接在kbe的demo上创建节点试试

**Comment by bowdar** [comment]
以前没用蓝图没发现，其实一直都这样，今天重新更新了一个最新干净版本，并且在完全没有动过的 kbengine_ue4_demo上创建节点，也不行。难道只有我遇到这个问题了么，我都换了电脑试的

**Comment by kbengine** [comment]
引擎版本？demo你不改动会崩溃吗

**Comment by bowdar** [comment]
4.15吧，我把UE4和kbengine_ue4_demo都重新check到最新版本，demo不改动不会崩，添加节点就崩

**Comment by kbengine** [comment]
我测试了并没有出现你的问题
![1](https://cloud.githubusercontent.com/assets/2336717/25078368/bfc7f896-2364-11e7-8ca3-af77f41d817f.png)
