### ISSUE TITLE
Events为空

### ISSUE THREAD

**Issue by tanyong5811** [kbengine/kbengine_ue4_demo#44]
你好，我碰到一个问题，困扰了好久， 就是UE4客户端中，一开始，创建登陆等都没问题，但是一旦跳转关卡，跳到一个新地图，所有注册得事件都会被清空，所以注册得，与Fire()事件也都会无效。这个怎么解决啊。
![QQ图片20190323193235](https://user-images.githubusercontent.com/28855148/54865577-71c09d00-4da2-11e9-8bce-c2e9a1f504d6.png)

**Comment by kebiao** [comment]
全部更新到最新master版本，服务器和客户端
