### ISSUE TITLE
UE4.19崩溃

### ISSUE THREAD

**Issue by canplay** [kbengine/kbengine_ue4_demo#7]
KBEnginePlugins
->KBEngine.cpp
->KBEngineApp::onUpdatePropertys_(ENTITY_ID eid, MemoryStream& stream)
->Property* propertydata = pdatas[utype];
看着像是没找到对应的属性？

**Comment by kebiao** [comment]
今天更新的demo？服务器脚本自己写的？

**Comment by canplay** [comment]
使用的4d029fd，22天前的demo

**Comment by canplay** [comment]
服务器脚本是2月8日的

**Comment by kebiao** [comment]
那你是用的2.0服务器？现在客户端不支持
